## DEFINING SERVICES
version: '3'

## CREATE DATABASE IMAGE ##
services:
 db:
  image: mysql:8.0
  container_name: db
  restart: unless-stopped
  env_file: .env
  environment:
   - MYSQL_DATABASE=wordpress
  volumes: 
   - db-vol:/var/lib/mysql
  command: '--default-authentication-plugin=mysql_native_password'
  networks:
   - wp-net
